from .libro import Libro as LibroResource
from .libro import Libros as LibrosResource
from .opinionLibro import Valoracion as ValoracionResource
from .opinionLibro import Comentario as ComentarioResource 
from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .signin_login import Sign_in as Sign_inResource
from .signin_login import Login as LoginResource
from .configuracion import Configuracion as ConfiguracionResource
from .notificacion import Notificacion as NotificacionResource
from .prestamos import Prestamos as PrestamosResource
from .prestamos import Prestamo as PrestamoResource
